#ifndef LIB_PSS_PSMMONOFUNC_H
#define LIB_PSS_PSMMONOFUNC_H 1

#include <Sce/Pss/Core/InitializeCsharp.hpp>
#include <LibPSM.hpp>

namespace Sce::Pss::Core::Mono {

	static PsmMonoFunc ErrorFunctions [] {
		{ "Sce.PlayStation.Core.Error::GetExceptionInfoNative(string&,string&)", Sce::Pss::Core::Error::GetExceptionInfoNative },
		{ nullptr, nullptr }
	};

	static PsmMonoFunc ServiceFunctions[] {
		{ "Sce.PlayStation.Core.Services.NetworkRequest::CreateRequestNative(int,string,string,int&)", Sce::Pss::Core::Services::NetworkRequest::CreateRequestNative },
		{ "Sce.PlayStation.Core.Services.NetworkRequest::QueueRequestNative(int,string,string,int&)", Sce::Pss::Core::Services::NetworkRequest::QueueRequestNative },
		{ "Sce.PlayStation.Core.Services.NetworkRequest::DestroyRequestNative(int)", Sce::Pss::Core::Services::NetworkRequest::DestroyRequestNative },
		{ "Sce.PlayStation.Core.Services.NetworkRequest::GetResponseNative(int,string&)", Sce::Pss::Core::Services::NetworkRequest::GetResponseNative },
		{ "Sce.PlayStation.Core.Services.NetworkRequest::RegisterThreadNative()", Sce::Pss::Core::Services::NetworkRequest::RegisterThreadNative },
		{ "Sce.PlayStation.Core.Services.NetworkRequest::UnregisterThreadNative()", Sce::Pss::Core::Services::NetworkRequest::UnregisterThreadNative },
		{ "Sce.PlayStation.Core.Services.Network::CheckStateNative(uint&)", Sce::Pss::Core::Services::Network::CheckStateNative },
		{ "Sce.PlayStation.Core.Services.Network::GetOnlineIdNative(string&)", Sce::Pss::Core::Services::Network::GetOnlineIdNative },
		{ "Sce.PlayStation.Core.Services.Network::GetAccountIdNative(ulong&)", Sce::Pss::Core::Services::Network::GetAccountIdNative },
		{ "Sce.PlayStation.Core.Services.Network::SetWebRequestDelegate(intptr)", Sce::Pss::Core::Services::Network::SetWebRequestDelegate },
		{ "Sce.PlayStation.Core.Services.Network::SetAuthServer(bool)", Sce::Pss::Core::Services::Network::SetAuthServer },
		{ "Sce.PlayStation.Core.Services.Network::GetAuthTicketDataNative(string&)", Sce::Pss::Core::Services::Network::GetAuthTicketDataNative },
		{ "Sce.PlayStation.Core.Services.Network::ResetAuthTicketNative()", Sce::Pss::Core::Services::Network::ResetAuthTicketNative },
		{ "Sce.PlayStation.Core.Services.Network::SetAppIdNative(string)", Sce::Pss::Core::Services::Network::SetAppIdNative },
		{ nullptr, nullptr }
	};

	static PsmMonoFunc CameraFunctions[] {
		{ "Sce.PlayStation.Core.Device.Camera::GetNumberOfCamerasNative()", Sce::Pss::Core::Device::Camera::GetNumberOfCamerasNative },
		{ "Sce.PlayStation.Core.Device.Camera::GetCameraFacingNative(int,Sce.PlayStation.Core.Device.CameraFacing&)", Sce::Pss::Core::Device::Camera::GetCameraFacingNative },
		{ "Sce.PlayStation.Core.Device.Camera::GetSupportedPreviewSizeCountNative(int)", Sce::Pss::Core::Device::Camera::GetSupportedPreviewSizeCountNative },
		{ "Sce.PlayStation.Core.Device.Camera::GetSupportedPreviewSizeNative(int,int,Sce.PlayStation.Core.Device.CameraSize&)", Sce::Pss::Core::Device::Camera::GetSupportedPreviewSizeNative },
		{ "Sce.PlayStation.Core.Device.Camera::GetSupportedPictureSizeCountNative(int)", Sce::Pss::Core::Device::Camera::GetSupportedPictureSizeCountNative },
		{ "Sce.PlayStation.Core.Device.Camera::GetSupportedPictureSizeNative(int,int,Sce.PlayStation.Core.Device.CameraSize&)", Sce::Pss::Core::Device::Camera::GetSupportedPictureSizeNative },
		{ "Sce.PlayStation.Core.Device.Camera::NewFromIndex(int,int&)", Sce::Pss::Core::Device::Camera::NewFromIndex },
		{ "Sce.PlayStation.Core.Device.Camera::ReleaseNative(int)", Sce::Pss::Core::Device::Camera::ReleaseNative },
		{ "Sce.PlayStation.Core.Device.Camera::GetCameraStateNative(int,Sce.PlayStation.Core.Device.CameraState&)", Sce::Pss::Core::Device::Camera::GetCameraStateNative },
		{ "Sce.PlayStation.Core.Device.Camera::HasTakenPictureNative(int,Sce.PlayStation.Core.Device.PictureState&)", Sce::Pss::Core::Device::Camera::HasTakenPictureNative },
		{ "Sce.PlayStation.Core.Device.Camera::OpenNative(int,Sce.PlayStation.Core.Device.CameraSize)", Sce::Pss::Core::Device::Camera::OpenNative },
		{ "Sce.PlayStation.Core.Device.Camera::CloseNative(int)", Sce::Pss::Core::Device::Camera::CloseNative },
		{ "Sce.PlayStation.Core.Device.Camera::GetPreviewSizeNative(int,Sce.PlayStation.Core.Device.CameraSize&)", Sce::Pss::Core::Device::Camera::GetPreviewSizeNative },
		{ "Sce.PlayStation.Core.Device.Camera::GetPreviewImageFormatNative(int,Sce.PlayStation.Core.Device.CameraImageFormat&)", Sce::Pss::Core::Device::Camera::GetPreviewImageFormatNative },
		{ "Sce.PlayStation.Core.Device.Camera::StartNative(int)", Sce::Pss::Core::Device::Camera::StartNative },
		{ "Sce.PlayStation.Core.Device.Camera::StopNative(int)", Sce::Pss::Core::Device::Camera::StopNative },
		{ "Sce.PlayStation.Core.Device.Camera::ReadNative(int,byte[],int,long&)", Sce::Pss::Core::Device::Camera::ReadNative },
		{ "Sce.PlayStation.Core.Device.Camera::TakePictureNative(int,Sce.PlayStation.Core.Device.CameraSize)", Sce::Pss::Core::Device::Camera::TakePictureNative },
		{ "Sce.PlayStation.Core.Device.Camera::GetPictureFilenameNative(int,string&)", Sce::Pss::Core::Device::Camera::GetPictureFilenameNative },
		{ nullptr, nullptr }

	};

	static PsmMonoFunc LocationFunctions[] {
		{ "Sce.PlayStation.Core.Device.Location::StartNative()", Sce::Pss::Core::Device::Location::StartNative },
		{ "Sce.PlayStation.Core.Device.Location::StopNative()", Sce::Pss::Core::Device::Location::StopNative },
		{ "Sce.PlayStation.Core.Device.Location::GetDataNative(Sce.PlayStation.Core.Device.LocationData&)", Sce::Pss::Core::Device::Location::GetDataNative },
		{ "Sce.PlayStation.Core.Device.Location::GetEnableDevicesNative()", Sce::Pss::Core::Device::Location::GetEnableDevicesNative },
		{ nullptr, nullptr }
	};

	static PsmMonoFunc ImagingFunctions[]{
		{ "Sce.PlayStation.Core.Imaging.Image::NewFromFilename(string,int&)", Sce::Pss::Core::Imaging::Image::NewFromFilename },
		{ "Sce.PlayStation.Core.Imaging.Image::NewFromFileImage(byte[],int&)", Sce::Pss::Core::Imaging::Image::NewFromFileImage },
		{ "Sce.PlayStation.Core.Imaging.Image::NewFromModeSizeColor(Sce.PlayStation.Core.Imaging.ImageMode,Sce.PlayStation.Core.Imaging.ImageSize&,Sce.PlayStation.Core.Imaging.ImageColor&,int&)", Sce::Pss::Core::Imaging::Image::NewFromModeSizeColor },
		{ "Sce.PlayStation.Core.Imaging.Image::NewFromModeSizeBuffer(Sce.PlayStation.Core.Imaging.ImageMode,Sce.PlayStation.Core.Imaging.ImageSize&,byte[],int&)", Sce::Pss::Core::Imaging::Image::NewFromModeSizeBuffer },
		{ "Sce.PlayStation.Core.Imaging.Image::AddRefNative(int)", Sce::Pss::Core::Imaging::Image::AddRefNative },
		{ "Sce.PlayStation.Core.Imaging.Image::ReleaseNative(int)", Sce::Pss::Core::Imaging::Image::ReleaseNative },
		{ "Sce.PlayStation.Core.Imaging.Image::GetSize(int,Sce.PlayStation.Core.Imaging.ImageSize&)", Sce::Pss::Core::Imaging::Image::GetSize },
		{ "Sce.PlayStation.Core.Imaging.Image::SetDecodeSize(int,Sce.PlayStation.Core.Imaging.ImageSize&)", Sce::Pss::Core::Imaging::Image::SetDecodeSize },
		{ "Sce.PlayStation.Core.Imaging.Image::DecodeNative(int)", Sce::Pss::Core::Imaging::Image::DecodeNative },
		{ "Sce.PlayStation.Core.Imaging.Image::GetPixelData(int,byte[],uint)", Sce::Pss::Core::Imaging::Image::GetPixelData },
		{ "Sce.PlayStation.Core.Imaging.Image::GetPixelDataSize(int,uint&)", Sce::Pss::Core::Imaging::Image::GetPixelDataSize },
		{ "Sce.PlayStation.Core.Imaging.Image::ResizeNative(int,Sce.PlayStation.Core.Imaging.ImageSize&,int&)", Sce::Pss::Core::Imaging::Image::ResizeNative },
		{ "Sce.PlayStation.Core.Imaging.Image::CropNative(int,Sce.PlayStation.Core.Imaging.ImageRect&,int&)", Sce::Pss::Core::Imaging::Image::CropNative },
		{ "Sce.PlayStation.Core.Imaging.Image::DrawImageNative(int,int,Sce.PlayStation.Core.Imaging.ImagePosition&)", Sce::Pss::Core::Imaging::Image::DrawImageNative },
		{ "Sce.PlayStation.Core.Imaging.Image::DrawRectangleNative(int,Sce.PlayStation.Core.Imaging.ImageColor&,Sce.PlayStation.Core.Imaging.ImageRect&)", Sce::Pss::Core::Imaging::Image::DrawRectangleNative },
		{ "Sce.PlayStation.Core.Imaging.Image::DrawTextNative(int,string,int,int,Sce.PlayStation.Core.Imaging.ImageColor&,int,Sce.PlayStation.Core.Imaging.ImagePosition&)", Sce::Pss::Core::Imaging::Image::DrawTextNative },
		{ "Sce.PlayStation.Core.Imaging.Image::ExportNative(int,string,string)", Sce::Pss::Core::Imaging::Image::ExportNative },
		{ "Sce.PlayStation.Core.Imaging.Image::SaveAsNative(int,string)", Sce::Pss::Core::Imaging::Image::SaveAsNative },
		{ "Sce.PlayStation.Core.Imaging.Font::NewFromFilenameSizeStyle(string,int,Sce.PlayStation.Core.Imaging.FontStyle,int&)", Sce::Pss::Core::Imaging::Font::NewFromFilenameSizeStyle },
		{ "Sce.PlayStation.Core.Imaging.Font::NewFromAliasSizeStyle(Sce.PlayStation.Core.Imaging.FontAlias,int,Sce.PlayStation.Core.Imaging.FontStyle,int&)", Sce::Pss::Core::Imaging::Font::NewFromAliasSizeStyle },
		{ "Sce.PlayStation.Core.Imaging.Font::AddRefNative(int)", Sce::Pss::Core::Imaging::Font::AddRefNative },
		{ "Sce.PlayStation.Core.Imaging.Font::ReleaseNative(int)", Sce::Pss::Core::Imaging::Font::ReleaseNative },
		{ "Sce.PlayStation.Core.Imaging.Font::GetName(int,string&)", Sce::Pss::Core::Imaging::Font::GetName },
		{ "Sce.PlayStation.Core.Imaging.Font::GetSize(int,int&)", Sce::Pss::Core::Imaging::Font::GetSize },
		{ "Sce.PlayStation.Core.Imaging.Font::GetStyle(int,Sce.PlayStation.Core.Imaging.FontStyle&)", Sce::Pss::Core::Imaging::Font::GetStyle },
		{ "Sce.PlayStation.Core.Imaging.Font::GetMetrics(int,Sce.PlayStation.Core.Imaging.FontMetrics&)", Sce::Pss::Core::Imaging::Font::GetMetrics },
		{ "Sce.PlayStation.Core.Imaging.Font::GetTextWidthNative(int,string,int,int,int&)", Sce::Pss::Core::Imaging::Font::GetTextWidthNative },
		{ "Sce.PlayStation.Core.Imaging.Font::GetTextMetricsNative(int,string,int,int,Sce.PlayStation.Core.Imaging.CharMetrics[])", Sce::Pss::Core::Imaging::Font::GetTextMetricsNative },
		{ nullptr, nullptr }
	};

	static PsmMonoFunc InputFunctions[] {
		{ "Sce.PlayStation.Core.Input.Touch::GetDataNative(int,Sce.PlayStation.Core.Input.TouchData[],int,int&)", Sce::Pss::Core::Input::Touch::GetDataNative },
		{ "Sce.PlayStation.Core.Input.Touch::GetRearTouchDataNative(int,Sce.PlayStation.Core.Input.TouchData[],int,int&)", Sce::Pss::Core::Input::Touch::GetRearTouchDataNative },
		{ "Sce.PlayStation.Core.Input.GamePad::GetDataNative(int,Sce.PlayStation.Core.Input.GamePadData&)", Sce::Pss::Core::Input::GamePad::GetDataNative },
		{ "Sce.PlayStation.Core.Input.Motion::GetDataNative(int,Sce.PlayStation.Core.Input.MotionData&)", Sce::Pss::Core::Input::Motion::GetDataNative },
		{ nullptr, nullptr }
	};

	static PsmMonoFunc AudioFunctions[]{
		{ "Sce.PlayStation.Core.Audio.Sound::NewFromFilename(string,int&)", Sce::Pss::Core::Audio::Sound::NewFromFilename },
		{ "Sce.PlayStation.Core.Audio.Sound::NewFromFileImage(byte[],int&)", Sce::Pss::Core::Audio::Sound::NewFromFileImage },
		{ "Sce.PlayStation.Core.Audio.Sound::ReleaseNative(int)", Sce::Pss::Core::Audio::Sound::ReleaseNative },
		{ "Sce.PlayStation.Core.Audio.Sound::CreatePlayerNative(int,int&)", Sce::Pss::Core::Audio::Sound::CreatePlayerNative },
		{ "Sce.PlayStation.Core.Audio.SoundPlayer::ReleaseNative(int)", Sce::Pss::Core::Audio::SoundPlayer::ReleaseNative },
		{ "Sce.PlayStation.Core.Audio.SoundPlayer::PlayNative(int)", Sce::Pss::Core::Audio::SoundPlayer::PlayNative },
		{ "Sce.PlayStation.Core.Audio.SoundPlayer::StopNative(int)", Sce::Pss::Core::Audio::SoundPlayer::StopNative },
		{ "Sce.PlayStation.Core.Audio.SoundPlayer::GetStatusNative(int,Sce.PlayStation.Core.Audio.SoundStatus&)", Sce::Pss::Core::Audio::SoundPlayer::GetStatusNative },
		{ "Sce.PlayStation.Core.Audio.SoundPlayer::GetVolumeNative(int,single&)", Sce::Pss::Core::Audio::SoundPlayer::GetVolumeNative },
		{ "Sce.PlayStation.Core.Audio.SoundPlayer::SetVolumeNative(int,single)", Sce::Pss::Core::Audio::SoundPlayer::SetVolumeNative },
		{ "Sce.PlayStation.Core.Audio.SoundPlayer::GetPanNative(int,single&)", Sce::Pss::Core::Audio::SoundPlayer::GetPanNative },
		{ "Sce.PlayStation.Core.Audio.SoundPlayer::SetPanNative(int,single)", Sce::Pss::Core::Audio::SoundPlayer::SetPanNative },
		{ "Sce.PlayStation.Core.Audio.SoundPlayer::GetLoopNative(int,bool&)", Sce::Pss::Core::Audio::SoundPlayer::GetLoopNative },
		{ "Sce.PlayStation.Core.Audio.SoundPlayer::SetLoopNative(int,bool)", Sce::Pss::Core::Audio::SoundPlayer::SetLoopNative },
		{ "Sce.PlayStation.Core.Audio.SoundPlayer::GetPlaybackRateNative(int,single&)", Sce::Pss::Core::Audio::SoundPlayer::GetPlaybackRateNative },
		{ "Sce.PlayStation.Core.Audio.SoundPlayer::SetPlaybackRateNative(int,single)", Sce::Pss::Core::Audio::SoundPlayer::SetPlaybackRateNative },
		{ "Sce.PlayStation.Core.Audio.SoundPlayer::GetPosition(int,ulong&)", Sce::Pss::Core::Audio::SoundPlayer::GetPosition },
		{ "Sce.PlayStation.Core.Audio.SoundPlayer::SetPosition(int,ulong)", Sce::Pss::Core::Audio::SoundPlayer::SetPosition },
		{ "Sce.PlayStation.Core.Audio.SoundPlayer::GetLength(int,ulong&)", Sce::Pss::Core::Audio::SoundPlayer::GetLength },
		{ "Sce.PlayStation.Core.Audio.Bgm::NewFromFilename(string,int&)", Sce::Pss::Core::Audio::Bgm::NewFromFilename },
		{ "Sce.PlayStation.Core.Audio.Bgm::NewFromFileImage(byte[],int&)", Sce::Pss::Core::Audio::Bgm::NewFromFileImage },
		{ "Sce.PlayStation.Core.Audio.Bgm::ReleaseNative(int)", Sce::Pss::Core::Audio::Bgm::ReleaseNative },
		{ "Sce.PlayStation.Core.Audio.Bgm::CreatePlayerNative(int,int&)", Sce::Pss::Core::Audio::Bgm::CreatePlayerNative },
		{ "Sce.PlayStation.Core.Audio.BgmPlayer::ReleaseNative(int)", Sce::Pss::Core::Audio::BgmPlayer::ReleaseNative },
		{ "Sce.PlayStation.Core.Audio.BgmPlayer::PlayNative(int)", Sce::Pss::Core::Audio::BgmPlayer::PlayNative },
		{ "Sce.PlayStation.Core.Audio.BgmPlayer::StopNative(int)", Sce::Pss::Core::Audio::BgmPlayer::StopNative },
		{ "Sce.PlayStation.Core.Audio.BgmPlayer::GetStatusNative(int,Sce.PlayStation.Core.Audio.BgmStatus&)", Sce::Pss::Core::Audio::BgmPlayer::GetStatusNative },
		{ "Sce.PlayStation.Core.Audio.BgmPlayer::PauseNative(int)", Sce::Pss::Core::Audio::BgmPlayer::PauseNative },
		{ "Sce.PlayStation.Core.Audio.BgmPlayer::ResumeNative(int)", Sce::Pss::Core::Audio::BgmPlayer::ResumeNative },
		{ "Sce.PlayStation.Core.Audio.BgmPlayer::SetVolumeNative(int,single)", Sce::Pss::Core::Audio::BgmPlayer::SetVolumeNative },
		{ "Sce.PlayStation.Core.Audio.BgmPlayer::GetVolumeNative(int,single&)", Sce::Pss::Core::Audio::BgmPlayer::GetVolumeNative },
		{ "Sce.PlayStation.Core.Audio.BgmPlayer::GetLoopNative(int,bool&)", Sce::Pss::Core::Audio::BgmPlayer::GetLoopNative },
		{ "Sce.PlayStation.Core.Audio.BgmPlayer::SetLoopNative(int,bool)", Sce::Pss::Core::Audio::BgmPlayer::SetLoopNative },
		{ "Sce.PlayStation.Core.Audio.BgmPlayer::GetPlaybackRateNative(int,single&)", Sce::Pss::Core::Audio::BgmPlayer::GetPlaybackRateNative },
		{ "Sce.PlayStation.Core.Audio.BgmPlayer::SetPlaybackRateNative(int,single)", Sce::Pss::Core::Audio::BgmPlayer::SetPlaybackRateNative },
		{ "Sce.PlayStation.Core.Audio.BgmPlayer::GetPosition(int,ulong&)", Sce::Pss::Core::Audio::BgmPlayer::GetPosition },
		{ "Sce.PlayStation.Core.Audio.BgmPlayer::SetPosition(int,ulong)", Sce::Pss::Core::Audio::BgmPlayer::SetPosition },
		{ "Sce.PlayStation.Core.Audio.BgmPlayer::GetLength(int,ulong&)", Sce::Pss::Core::Audio::BgmPlayer::GetLength },
		{ "Sce.PlayStation.Core.Audio.BgmPlayer::GetLoopPosition(int,ulong&,ulong&)", Sce::Pss::Core::Audio::BgmPlayer::GetLoopPosition },
		{ "Sce.PlayStation.Core.Audio.BgmPlayer::SetLoopPosition(int,ulong,ulong)", Sce::Pss::Core::Audio::BgmPlayer::SetLoopPosition },
		{ nullptr, nullptr }
	};

	static PsmMonoFunc GraphicsFunctions[]{
		{ "Sce.PlayStation.Core.Graphics.PsmGraphicsContext::Create(int,int,Sce.PlayStation.Core.Graphics.PixelFormat,Sce.PlayStation.Core.Graphics.PixelFormat,Sce.PlayStation.Core.Graphics.MultiSampleMode,int&)", Sce::Pss::Core::Graphics::PsmGraphicsContext::Create },
		{ "Sce.PlayStation.Core.Graphics.PsmGraphicsContext::Delete(int)", Sce::Pss::Core::Graphics::PsmGraphicsContext::Delete },
		{ "Sce.PlayStation.Core.Graphics.PsmGraphicsContext::Update(int,Sce.PlayStation.Core.Graphics.GraphicsUpdate,Sce.PlayStation.Core.Graphics.GraphicsState&,int[])", Sce::Pss::Core::Graphics::PsmGraphicsContext::Update },
		{ "Sce.PlayStation.Core.Graphics.PsmGraphicsContext::SwapBuffers(int)", Sce::Pss::Core::Graphics::PsmGraphicsContext::SwapBuffers },
		{ "Sce.PlayStation.Core.Graphics.PsmGraphicsContext::Clear(int,Sce.PlayStation.Core.Graphics.ClearMask)", Sce::Pss::Core::Graphics::PsmGraphicsContext::Clear },
		{ "Sce.PlayStation.Core.Graphics.PsmGraphicsContext::DrawArrays(int,Sce.PlayStation.Core.Graphics.DrawMode,int,int,int)", Sce::Pss::Core::Graphics::PsmGraphicsContext::DrawArrays },
		{ "Sce.PlayStation.Core.Graphics.PsmGraphicsContext::DrawArrays2(int,Sce.PlayStation.Core.Graphics.Primitive[],int,int)", Sce::Pss::Core::Graphics::PsmGraphicsContext::DrawArrays2 },
		{ "Sce.PlayStation.Core.Graphics.PsmGraphicsContext::DrawArraysInstanced(int,Sce.PlayStation.Core.Graphics.DrawMode,int,int,int,int)", Sce::Pss::Core::Graphics::PsmGraphicsContext::DrawArraysInstanced },
		{ "Sce.PlayStation.Core.Graphics.PsmGraphicsContext::ReadPixels(int,byte[],Sce.PlayStation.Core.Graphics.PixelFormat,int,int,int,int)", Sce::Pss::Core::Graphics::PsmGraphicsContext::ReadPixels },
		{ "Sce.PlayStation.Core.Graphics.PsmGraphicsContext::ReadPixels2(int,int,int,Sce.PlayStation.Core.Graphics.TextureCubeFace,int,int,int,int,int,int)", Sce::Pss::Core::Graphics::PsmGraphicsContext::ReadPixels2 },
		{ "Sce.PlayStation.Core.Graphics.PsmGraphicsContext::GetMaxScreenSize(int&,int&)", Sce::Pss::Core::Graphics::PsmGraphicsContext::GetMaxScreenSize },
		{ "Sce.PlayStation.Core.Graphics.PsmGraphicsContext::GetScreenSizes(Sce.PlayStation.Core.Imaging.ImageSize[],int&)", Sce::Pss::Core::Graphics::PsmGraphicsContext::GetScreenSizes },
		{ "Sce.PlayStation.Core.Graphics.PsmGraphicsContext::GetScreenInfo(int,int&,int&,Sce.PlayStation.Core.Graphics.PixelFormat&,Sce.PlayStation.Core.Graphics.PixelFormat&,Sce.PlayStation.Core.Graphics.MultiSampleMode&)", Sce::Pss::Core::Graphics::PsmGraphicsContext::GetScreenInfo },
		{ "Sce.PlayStation.Core.Graphics.PsmGraphicsContext::GetCaps(int,Sce.PlayStation.Core.Graphics.GraphicsCapsState&)", Sce::Pss::Core::Graphics::PsmGraphicsContext::GetCaps },
		{ "Sce.PlayStation.Core.Graphics.PsmGraphicsContext::SetActiveScreen(int,int,int,int,int)", Sce::Pss::Core::Graphics::PsmGraphicsContext::SetActiveScreen },
		{ "Sce.PlayStation.Core.Graphics.PsmGraphicsContext::SetVirtualScreen(int,int,int,int,int)", Sce::Pss::Core::Graphics::PsmGraphicsContext::SetVirtualScreen },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::FromFile(string,string,string[],int[],int&)", Sce::Pss::Core::Graphics::PsmShaderProgram::FromFile },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::FromImage(byte[],byte[],string[],int[],int&)", Sce::Pss::Core::Graphics::PsmShaderProgram::FromImage },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::Delete(int)", Sce::Pss::Core::Graphics::PsmShaderProgram::Delete },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::AddRef(int)", Sce::Pss::Core::Graphics::PsmShaderProgram::AddRef },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::GetUniformCount(int,int&)", Sce::Pss::Core::Graphics::PsmShaderProgram::GetUniformCount },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::GetAttributeCount(int,int&)", Sce::Pss::Core::Graphics::PsmShaderProgram::GetAttributeCount },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::FindUniform(int,string,int&)", Sce::Pss::Core::Graphics::PsmShaderProgram::FindUniform },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::FindAttribute(int,string,int&)", Sce::Pss::Core::Graphics::PsmShaderProgram::FindAttribute },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::GetUniformBinding(int,int,string&)", Sce::Pss::Core::Graphics::PsmShaderProgram::GetUniformBinding },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::SetUniformBinding(int,int,string)", Sce::Pss::Core::Graphics::PsmShaderProgram::SetUniformBinding },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::GetAttributeBinding(int,int,string&)", Sce::Pss::Core::Graphics::PsmShaderProgram::GetAttributeBinding },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::SetAttributeBinding(int,int,string)", Sce::Pss::Core::Graphics::PsmShaderProgram::SetAttributeBinding },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::GetUniformType(int,int,Sce.PlayStation.Core.Graphics.ShaderUniformType&)", Sce::Pss::Core::Graphics::PsmShaderProgram::GetUniformType },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::GetAttributeType(int,int,Sce.PlayStation.Core.Graphics.ShaderAttributeType&)", Sce::Pss::Core::Graphics::PsmShaderProgram::GetAttributeType },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::GetUniformName(int,int,string&)", Sce::Pss::Core::Graphics::PsmShaderProgram::GetUniformName },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::GetAttributeName(int,int,string&)", Sce::Pss::Core::Graphics::PsmShaderProgram::GetAttributeName },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::GetUniformSize(int,int,int&)", Sce::Pss::Core::Graphics::PsmShaderProgram::GetUniformSize },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::GetAttributeSize(int,int,int&)", Sce::Pss::Core::Graphics::PsmShaderProgram::GetAttributeSize },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::SetUniformValue(int,int,int,Sce.PlayStation.Core.Matrix4&,Sce.PlayStation.Core.Graphics.ShaderUniformType)", Sce::Pss::Core::Graphics::PsmShaderProgram::SetUniformValue },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::SetUniformValue(int,int,int,Sce.PlayStation.Core.Vector4&,Sce.PlayStation.Core.Graphics.ShaderUniformType)", Sce::Pss::Core::Graphics::PsmShaderProgram::SetUniformValue },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::SetUniformValue(int,int,int,Sce.PlayStation.Core.Vector3&,Sce.PlayStation.Core.Graphics.ShaderUniformType)", Sce::Pss::Core::Graphics::PsmShaderProgram::SetUniformValue },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::SetUniformValue(int,int,int,Sce.PlayStation.Core.Vector2&,Sce.PlayStation.Core.Graphics.ShaderUniformType)", Sce::Pss::Core::Graphics::PsmShaderProgram::SetUniformValue },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::SetUniformValue(int,int,int,single&,Sce.PlayStation.Core.Graphics.ShaderUniformType)", Sce::Pss::Core::Graphics::PsmShaderProgram::SetUniformValue },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::SetUniformValue(int,int,int,int&,Sce.PlayStation.Core.Graphics.ShaderUniformType)", Sce::Pss::Core::Graphics::PsmShaderProgram::SetUniformValue },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::SetUniformValue2(int,int,Sce.PlayStation.Core.Matrix4[],Sce.PlayStation.Core.Graphics.ShaderUniformType,int,int,int)", Sce::Pss::Core::Graphics::PsmShaderProgram::SetUniformValue2 },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::SetUniformValue2(int,int,Sce.PlayStation.Core.Vector4[],Sce.PlayStation.Core.Graphics.ShaderUniformType,int,int,int)", Sce::Pss::Core::Graphics::PsmShaderProgram::SetUniformValue2 },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::SetUniformValue2(int,int,Sce.PlayStation.Core.Vector3[],Sce.PlayStation.Core.Graphics.ShaderUniformType,int,int,int)", Sce::Pss::Core::Graphics::PsmShaderProgram::SetUniformValue2 },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::SetUniformValue2(int,int,Sce.PlayStation.Core.Vector2[],Sce.PlayStation.Core.Graphics.ShaderUniformType,int,int,int)", Sce::Pss::Core::Graphics::PsmShaderProgram::SetUniformValue2 },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::SetUniformValue2(int,int,single[],Sce.PlayStation.Core.Graphics.ShaderUniformType,int,int,int)", Sce::Pss::Core::Graphics::PsmShaderProgram::SetUniformValue2 },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::SetUniformValue2(int,int,int[],Sce.PlayStation.Core.Graphics.ShaderUniformType,int,int,int)", Sce::Pss::Core::Graphics::PsmShaderProgram::SetUniformValue2 },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::SetAttributeValue2(int,int,single[])", Sce::Pss::Core::Graphics::PsmShaderProgram::SetAttributeValue2 },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::GetUniformTexture(int,int,int&)", Sce::Pss::Core::Graphics::PsmShaderProgram::GetUniformTexture },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::GetAttributeStream(int,int,int&)", Sce::Pss::Core::Graphics::PsmShaderProgram::GetAttributeStream },
		{ "Sce.PlayStation.Core.Graphics.PsmShaderProgram::SetAttributeStream(int,int,int)", Sce::Pss::Core::Graphics::PsmShaderProgram::SetAttributeStream },
		{ "Sce.PlayStation.Core.Graphics.PsmVertexBuffer::Create(int,int,int,int,Sce.PlayStation.Core.Graphics.VertexFormat[],int&)", Sce::Pss::Core::Graphics::PsmVertexBuffer::Create },
		{ "Sce.PlayStation.Core.Graphics.PsmVertexBuffer::Delete(int)", Sce::Pss::Core::Graphics::PsmVertexBuffer::Delete },
		{ "Sce.PlayStation.Core.Graphics.PsmVertexBuffer::AddRef(int)", Sce::Pss::Core::Graphics::PsmVertexBuffer::AddRef },
		{ "Sce.PlayStation.Core.Graphics.PsmVertexBuffer::SetVertices(int,System.Array,int,int,int)", Sce::Pss::Core::Graphics::PsmVertexBuffer::SetVertices },
		{ "Sce.PlayStation.Core.Graphics.PsmVertexBuffer::SetVertices2(int,int,System.Array,Sce.PlayStation.Core.Graphics.VertexFormat,Sce.PlayStation.Core.Vector4&,Sce.PlayStation.Core.Vector4&,int,int,int,int,int)", Sce::Pss::Core::Graphics::PsmVertexBuffer::SetVertices2 },
		{ "Sce.PlayStation.Core.Graphics.PsmVertexBuffer::SetIndices(int,uint16[],int,int,int)", Sce::Pss::Core::Graphics::PsmVertexBuffer::SetIndices },
		{ "Sce.PlayStation.Core.Graphics.PsmPixelBuffer::Create(Sce.PlayStation.Core.Graphics.PixelBufferType,int,int,bool,Sce.PlayStation.Core.Graphics.PixelFormat,Sce.PlayStation.Core.Graphics.PixelBufferOption,Sce.PlayStation.Core.Graphics.InternalOption,int&)", Sce::Pss::Core::Graphics::PsmPixelBuffer::Create },
		{ "Sce.PlayStation.Core.Graphics.PsmPixelBuffer::Delete(int)", Sce::Pss::Core::Graphics::PsmPixelBuffer::Delete },
		{ "Sce.PlayStation.Core.Graphics.PsmPixelBuffer::AddRef(int)", Sce::Pss::Core::Graphics::PsmPixelBuffer::AddRef },
		{ "Sce.PlayStation.Core.Graphics.PsmPixelBuffer::GetInfo(int,Sce.PlayStation.Core.Graphics.PixelBufferType&,int&,int&,int&,Sce.PlayStation.Core.Graphics.PixelFormat&,Sce.PlayStation.Core.Graphics.PixelBufferOption&)", Sce::Pss::Core::Graphics::PsmPixelBuffer::GetInfo },
		{ "Sce.PlayStation.Core.Graphics.PsmTexture::FromFile(Sce.PlayStation.Core.Graphics.PixelBufferType,string,bool,Sce.PlayStation.Core.Graphics.PixelFormat,int&)", Sce::Pss::Core::Graphics::PsmTexture::FromFile },
		{ "Sce.PlayStation.Core.Graphics.PsmTexture::FromImage(Sce.PlayStation.Core.Graphics.PixelBufferType,byte[],bool,Sce.PlayStation.Core.Graphics.PixelFormat,int&)", Sce::Pss::Core::Graphics::PsmTexture::FromImage },
		{ "Sce.PlayStation.Core.Graphics.PsmTexture::SetFilter(int,Sce.PlayStation.Core.Graphics.TextureFilter&)", Sce::Pss::Core::Graphics::PsmTexture::SetFilter },
		{ "Sce.PlayStation.Core.Graphics.PsmTexture::SetWrap(int,Sce.PlayStation.Core.Graphics.TextureWrap&)", Sce::Pss::Core::Graphics::PsmTexture::SetWrap },
		{ "Sce.PlayStation.Core.Graphics.PsmTexture::SetMaxAnisotropy(int,single)", Sce::Pss::Core::Graphics::PsmTexture::SetMaxAnisotropy },
		{ "Sce.PlayStation.Core.Graphics.PsmTexture::SetPixels(int,int,Sce.PlayStation.Core.Graphics.TextureCubeFace,System.Array,Sce.PlayStation.Core.Graphics.PixelFormat,int,int,int,int,int,int)", Sce::Pss::Core::Graphics::PsmTexture::SetPixels },
		{ "Sce.PlayStation.Core.Graphics.PsmTexture::GenerateMipmap(int)", Sce::Pss::Core::Graphics::PsmTexture::GenerateMipmap },
		{ "Sce.PlayStation.Core.Graphics.PsmFrameBuffer::Create(int&)", Sce::Pss::Core::Graphics::PsmFrameBuffer::Create },
		{ "Sce.PlayStation.Core.Graphics.PsmFrameBuffer::Delete(int)", Sce::Pss::Core::Graphics::PsmFrameBuffer::Delete },
		{ "Sce.PlayStation.Core.Graphics.PsmFrameBuffer::AddRef(int)", Sce::Pss::Core::Graphics::PsmFrameBuffer::AddRef },
		{ "Sce.PlayStation.Core.Graphics.PsmFrameBuffer::SetColorTarget(int,int,int,Sce.PlayStation.Core.Graphics.TextureCubeFace,int&)", Sce::Pss::Core::Graphics::PsmFrameBuffer::SetColorTarget },
		{ "Sce.PlayStation.Core.Graphics.PsmFrameBuffer::SetDepthTarget(int,int,int,Sce.PlayStation.Core.Graphics.TextureCubeFace,int&)", Sce::Pss::Core::Graphics::PsmFrameBuffer::SetDepthTarget },
		{ nullptr, nullptr }
	};

	static PsmMonoFunc EnvironmentFunctions[] {
		{ "Sce.PlayStation.Core.Environment.Log::WriteNative(string)", Sce::Pss::Core::Environment::Log::WriteNative },
		{ "Sce.PlayStation.Core.Environment.Log::GetNeedsRedirection()", Sce::Pss::Core::Environment::Log::GetNeedsRedirection },
		{ "Sce.PlayStation.Core.Environment.SystemEvents::CheckEventsNative(Sce.PlayStation.Core.Environment.SystemEvents/InternalData&)", Sce::Pss::Core::Environment::SystemEvents::CheckEventsNative },
		{ "Sce.PlayStation.Core.Environment.SystemParameters::GetInt(Sce.PlayStation.Core.Environment.SystemParameters/ParameterKey,int&)", Sce::Pss::Core::Environment::SystemParameters::GetInt },
		{ "Sce.PlayStation.Core.Environment.SystemParameters::GetFloat(Sce.PlayStation.Core.Environment.SystemParameters/ParameterKey,single&)", Sce::Pss::Core::Environment::SystemParameters::GetFloat },
		{ "Sce.PlayStation.Core.Environment.SystemParameters::GetString(Sce.PlayStation.Core.Environment.SystemParameters/ParameterKey,string&)", Sce::Pss::Core::Environment::SystemParameters::GetString },
		{ "Sce.PlayStation.Core.Environment.SystemMemory::GetMemoryUsage(bool)", Sce::Pss::Core::Environment::SystemMemory::GetMemoryUsage },
		{ "Sce.PlayStation.Core.Environment.PersistentMemory::WriteNative(byte[])", Sce::Pss::Core::Environment::PersistentMemory::WriteNative },
		{ "Sce.PlayStation.Core.Environment.PersistentMemory::ReadNative(byte[])", Sce::Pss::Core::Environment::PersistentMemory::ReadNative },
		{ "Sce.PlayStation.Core.Environment.Shell::ExecuteNative(Sce.PlayStation.Core.Environment.Shell/Action&)", Sce::Pss::Core::Environment::Shell::ExecuteNative },
		{ "Sce.PlayStation.Core.Environment.TextInputDialog::NewNative(Sce.PlayStation.Core.Environment.CommonDialogType,int&)", Sce::Pss::Core::Environment::CommonDialog::NewNative },
		{ "Sce.PlayStation.Core.Environment.TextInputDialog::ReleaseNative(Sce.PlayStation.Core.Environment.CommonDialogType,int)", Sce::Pss::Core::Environment::CommonDialog::ReleaseNative },
		{ "Sce.PlayStation.Core.Environment.TextInputDialog::OpenNative(Sce.PlayStation.Core.Environment.CommonDialogType,int,Sce.PlayStation.Core.Environment.TextInputDialog/Arguments&)", Sce::Pss::Core::Environment::CommonDialog::OpenNative },
		{ "Sce.PlayStation.Core.Environment.TextInputDialog::AbortNative(Sce.PlayStation.Core.Environment.CommonDialogType,int)", Sce::Pss::Core::Environment::CommonDialog::AbortNative },
		{ "Sce.PlayStation.Core.Environment.TextInputDialog::GetState(Sce.PlayStation.Core.Environment.CommonDialogType,int,Sce.PlayStation.Core.Environment.CommonDialogState&)", Sce::Pss::Core::Environment::CommonDialog::GetState },
		{ "Sce.PlayStation.Core.Environment.TextInputDialog::GetResult(Sce.PlayStation.Core.Environment.CommonDialogType,int,Sce.PlayStation.Core.Environment.CommonDialogResult&,Sce.PlayStation.Core.Environment.TextInputDialog/Results&)", Sce::Pss::Core::Environment::CommonDialog::GetResult },
		{ "Sce.PlayStation.Core.Services.AccountInformation::GetUniqueID(byte[])", Sce::Pss::Core::Services::AccountInformation::GetUniqueID },
		{ "Sce.PlayStation.Core.Services.InAppPurchaseDialog::NewNative(int,int&)", Sce::Pss::Core::Environment::CommonDialog::NewNative },
		{ "Sce.PlayStation.Core.Services.InAppPurchaseDialog::ReleaseNative(int,int)", Sce::Pss::Core::Environment::CommonDialog::ReleaseNative },
		{ "Sce.PlayStation.Core.Services.InAppPurchaseDialog::OpenNative(int,int,Sce.PlayStation.Core.Services.InAppPurchaseDialog/CommandArguments&)", Sce::Pss::Core::Environment::CommonDialog::OpenNative },
		{ "Sce.PlayStation.Core.Services.InAppPurchaseDialog::AbortNative(int,int)", Sce::Pss::Core::Environment::CommonDialog::AbortNative },
		{ "Sce.PlayStation.Core.Services.InAppPurchaseDialog::GetState(int,int,Sce.PlayStation.Core.Environment.CommonDialogState&)", Sce::Pss::Core::Environment::CommonDialog::GetState },
		{ "Sce.PlayStation.Core.Services.InAppPurchaseDialog::GetResult(int,int,Sce.PlayStation.Core.Environment.CommonDialogResult&,Sce.PlayStation.Core.Services.InAppPurchaseDialog/CommandResults&)", Sce::Pss::Core::Environment::CommonDialog::GetResult },
		{ "Sce.PlayStation.Core.Environment.Clipboard::SetTextNative(string)", Sce::Pss::Core::Environment::Clipboard::SetTextNative },
		{ "Sce.PlayStation.Core.Environment.Clipboard::GetTextNative(string&)", Sce::Pss::Core::Environment::Clipboard::GetTextNative },
		{ "Sce.PlayStation.Core.Environment.NetworkInformation::GetNetworkInterfaceTypeNative()", Sce::Pss::Core::Environment::NetworkInformation::GetNetworkInterfaceTypeNative },
		{ "Sce.PlayStation.Core.Device.CameraImportDialog::NewNative(int,int&)", Sce::Pss::Core::Environment::CommonDialog::NewNative },
		{ "Sce.PlayStation.Core.Device.CameraImportDialog::ReleaseNative(int,int)", Sce::Pss::Core::Environment::CommonDialog::ReleaseNative },
		{ "Sce.PlayStation.Core.Device.CameraImportDialog::OpenNative(int,int,Sce.PlayStation.Core.Device.CameraImportDialog/DialogArguments&)", Sce::Pss::Core::Environment::CommonDialog::OpenNative },
		{ "Sce.PlayStation.Core.Device.CameraImportDialog::AbortNative(int,int)", Sce::Pss::Core::Environment::CommonDialog::AbortNative },
		{ "Sce.PlayStation.Core.Device.CameraImportDialog::GetState(int,int,Sce.PlayStation.Core.Environment.CommonDialogState&)", Sce::Pss::Core::Environment::CommonDialog::GetState },
		{ "Sce.PlayStation.Core.Device.CameraImportDialog::GetResult(int,int,Sce.PlayStation.Core.Environment.CommonDialogResult&,Sce.PlayStation.Core.Device.CameraImportDialog/DialogResults&)", Sce::Pss::Core::Environment::CommonDialog::GetResult },
		{ "Sce.PlayStation.Core.Device.PhotoImportDialog::NewNative(int,int&)", Sce::Pss::Core::Environment::CommonDialog::NewNative },
		{ "Sce.PlayStation.Core.Device.PhotoImportDialog::ReleaseNative(int,int)", Sce::Pss::Core::Environment::CommonDialog::ReleaseNative },
		{ "Sce.PlayStation.Core.Device.PhotoImportDialog::OpenNative(int,int,Sce.PlayStation.Core.Device.PhotoImportDialog/DialogArguments&)", Sce::Pss::Core::Environment::CommonDialog::OpenNative },
		{ "Sce.PlayStation.Core.Device.PhotoImportDialog::AbortNative(int,int)", Sce::Pss::Core::Environment::CommonDialog::AbortNative },
		{ "Sce.PlayStation.Core.Device.PhotoImportDialog::GetState(int,int,Sce.PlayStation.Core.Environment.CommonDialogState&)", Sce::Pss::Core::Environment::CommonDialog::GetState },
		{ "Sce.PlayStation.Core.Device.PhotoImportDialog::GetResult(int,int,Sce.PlayStation.Core.Environment.CommonDialogResult&,Sce.PlayStation.Core.Device.PhotoImportDialog/DialogResults&)", Sce::Pss::Core::Environment::CommonDialog::GetResult },
		{ nullptr, nullptr }
	};
}

#endif