on:
  push:
    branches:
      - main
jobs:
  ubuntu_meson_build:
    name: Linux (GCC)
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get submodules
        run: git submodule update --init --recursive
      - name: install dependencies
        run: |
            sudo apt update
            sudo apt install -y build-essential meson ninja libsdl2-dev mesa-utils libglu1-mesa-dev freeglut3-dev mesa-common-dev
      - name: compile
        run: |
            meson setup build
            cd build
            ninja
      - name: upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: SnowPME-Ubuntu
          path: build
  windows_msvc_build:
    name: Windows (Microsoft Visual C++)
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get submodules
        run: git submodule update --init --recursive
      - name: run msvc developer command prompt
        uses: TheMrMilchmann/setup-msvc-dev@v3.0.1
        with:
          arch: x86
      - name: compile
        run: msbuild SnowPME.sln /p:Configuration=Release_Static /p:Platform=Win32
      - name: upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: SnowPME-Windows
          path: build/SnowPME/bin
