on:
  push:
    branches:
      - main
jobs:
  build_msvc:
    name: run msvc build
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get submodules
        run: git submodule update --init --recursive
      - name: setup msvc developer command prompt
        uses: TheMrMilchmann/setup-msvc-dev@v3.0.1
        with:
          arch: x86
      - name: add windows xp support
        run: '&"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" modify --installPath "C:\Program Files\Microsoft Visual Studio\2022\Preview" --add Microsoft.VisualStudio.Component.WinXP --quiet --norestart --nocache'
      - name: msbuild
        run: msbuild SnowPME.sln /p:Configuration=Release_Static /p:Platform=Win32
