on:
  push:
    branches:
      - main
jobs:
  msvc_build:
    name: run msvc build
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get submodules
        run: git submodule update --init --recursive
      - name: add windows xp support
        run: |
          Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
          $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
          $WorkLoads = '--add Microsoft.VisualStudio.Component.WinXP'
          $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"", $WorkLoads, '--quiet', '--norestart', '--nocache')
          $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
          if ($process.ExitCode -eq 0)
          {
            Write-Host "components have been successfully added"
          }
          else
          {
            Write-Host "components were not installed"
            exit 1
          }
      - name: setup msvc developer command prompt
        uses: TheMrMilchmann/setup-msvc-dev@v3.0.1
        with:
          arch: x86
      - name: msbuild
        run: msbuild SnowPME.sln /p:Configuration=Release_Static /p:Platform=Win32
      - name: upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: SnowPME-MSVC
          path: build/SnowPME/bin
